/**
 * @packageDocumentation
 * @module api.functional.test_logs.executions.batch_logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { Recordstringunknown } from "../../../../structures/Recordstringunknown";

/**
 * @controller TestLogsController.sendBatchLogs
 * @path POST /test-logs/executions/:id/batch-logs
 * @accessor api.functional.test_logs.executions.batch_logs.sendBatchLogs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function sendBatchLogs(
  connection: IConnection,
  executionId: string,
  dto: sendBatchLogs.Body,
): Promise<sendBatchLogs.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...sendBatchLogs.METADATA,
      template: sendBatchLogs.METADATA.path,
      path: sendBatchLogs.path(executionId),
    },
    dto,
  );
}
export namespace sendBatchLogs {
  export type Body = {
    count: number;
    delay?: undefined | number;
  };
  export type Output = Recordstringunknown;

  export const METADATA = {
    method: "POST",
    path: "/test-logs/executions/:id/batch-logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (executionId: string) =>
    `/test-logs/executions/${encodeURIComponent(executionId?.toString() ?? "null")}/batch-logs`;
}
