/**
 * @packageDocumentation
 * @module api.functional.test_logs.aws_codebuild.seed
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller TestLogsController.createAwsCodeBuildExecution
 * @path POST /test-logs/aws-codebuild/seed
 * @accessor api.functional.test_logs.aws_codebuild.seed.createAwsCodeBuildExecution
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createAwsCodeBuildExecution(
  connection: IConnection,
): Promise<createAwsCodeBuildExecution.Output> {
  return PlainFetcher.fetch(connection, {
    ...createAwsCodeBuildExecution.METADATA,
    template: createAwsCodeBuildExecution.METADATA.path,
    path: createAwsCodeBuildExecution.path(),
  });
}
export namespace createAwsCodeBuildExecution {
  export type Output = any;

  export const METADATA = {
    method: "POST",
    path: "/test-logs/aws-codebuild/seed",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/test-logs/aws-codebuild/seed";
}
