[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node --max-old-space-size=512 dist/main.js"

[variables]
NODE_OPTIONS = "--max-old-space-size=512"
NODE_ENV = "production"