/**
 * @packageDocumentation
 * @module api.functional.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { UserResponse } from "../../structures/UserResponse";

/**
 * @controller UserController.userGetMyInfo
 * @path GET /user
 * @accessor api.functional.user.userGetMyInfo
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function userGetMyInfo(
  connection: IConnection,
): Promise<userGetMyInfo.Output> {
  return PlainFetcher.fetch(connection, {
    ...userGetMyInfo.METADATA,
    template: userGetMyInfo.METADATA.path,
    path: userGetMyInfo.path(),
  });
}
export namespace userGetMyInfo {
  export type Output = UserResponse;

  export const METADATA = {
    method: "GET",
    path: "/user",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/user";
}
