/**
 * @packageDocumentation
 * @module api.functional.webhook
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as github from "./github/index";
