/**
 * @packageDocumentation
 * @module api.functional.github_app.repositories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { GithubRepositoryResponseDto } from "../../../structures/GithubRepositoryResponseDto";

/**
 * @tag github-app
 * @summary 사용자가 접근할 수 있는 모든 리포지토리 조회
 * @throws 401 인증 실패
 * @controller GithubAppController.getUserRepositories
 * @path GET /github-app/repositories
 * @accessor api.functional.github_app.repositories.getUserRepositories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserRepositories(
  connection: IConnection,
): Promise<getUserRepositories.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserRepositories.METADATA,
    template: getUserRepositories.METADATA.path,
    path: getUserRepositories.path(),
  });
}
export namespace getUserRepositories {
  export type Output = GithubRepositoryResponseDto[];

  export const METADATA = {
    method: "GET",
    path: "/github-app/repositories",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/github-app/repositories";
}
