/**
 * @packageDocumentation
 * @module api.functional.auth.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { LoginResponseDto } from "../../../structures/LoginResponseDto";

/**
 * @tag auth
 * @summary Refresh Token으로 로그인
 * @throws 401 Refresh Token이 유효하지 않음
 * @controller AuthController.authRefreshSignIn
 * @path POST /auth/refresh
 * @accessor api.functional.auth.refresh.authRefreshSignIn
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authRefreshSignIn(
  connection: IConnection,
): Promise<authRefreshSignIn.Output> {
  return PlainFetcher.fetch(connection, {
    ...authRefreshSignIn.METADATA,
    template: authRefreshSignIn.METADATA.path,
    path: authRefreshSignIn.path(),
  });
}
export namespace authRefreshSignIn {
  export type Output = LoginResponseDto;

  export const METADATA = {
    method: "POST",
    path: "/auth/refresh",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/refresh";
}
