/**
 * @packageDocumentation
 * @module api.functional.logs.executions.status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { UpdateStatusDto } from "../../../../structures/UpdateStatusDto";

/**
 * @controller LogsController.updateExecutionStatus
 * @path PATCH /logs/executions/:id/status
 * @accessor api.functional.logs.executions.status.updateExecutionStatus
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateExecutionStatus(
  connection: IConnection,
  id: string,
  dto: updateExecutionStatus.Body,
): Promise<updateExecutionStatus.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateExecutionStatus.METADATA,
      template: updateExecutionStatus.METADATA.path,
      path: updateExecutionStatus.path(id),
    },
    dto,
  );
}
export namespace updateExecutionStatus {
  export type Body = UpdateStatusDto;
  export type Output = any;

  export const METADATA = {
    method: "PATCH",
    path: "/logs/executions/:id/status",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/logs/executions/${encodeURIComponent(id?.toString() ?? "null")}/status`;
}
