/**
 * @packageDocumentation
 * @module api.functional.github_app.installations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { GithubInstallationResponseDto } from "../../../structures/GithubInstallationResponseDto";

export * as repositories from "./repositories/index";

/**
 * @tag github-app
 * @summary 사용자의 GitHub App 설치 목록 조회
 * @throws 401 인증 실패
 * @controller GithubAppController.getUserInstallations
 * @path GET /github-app/installations
 * @accessor api.functional.github_app.installations.getUserInstallations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserInstallations(
  connection: IConnection,
): Promise<getUserInstallations.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserInstallations.METADATA,
    template: getUserInstallations.METADATA.path,
    path: getUserInstallations.path(),
  });
}
export namespace getUserInstallations {
  export type Output = GithubInstallationResponseDto[];

  export const METADATA = {
    method: "GET",
    path: "/github-app/installations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/github-app/installations";
}
