/**
 * @packageDocumentation
 * @module api.functional.auth.logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @tag auth
 * @summary 로그아웃
 * @controller AuthController.authSignOut
 * @path POST /auth/logout
 * @accessor api.functional.auth.logout.authSignOut
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authSignOut(
  connection: IConnection,
): Promise<authSignOut.Output> {
  return PlainFetcher.fetch(connection, {
    ...authSignOut.METADATA,
    template: authSignOut.METADATA.path,
    path: authSignOut.path(),
  });
}
export namespace authSignOut {
  export type Output = {
    message: string;
  };

  export const METADATA = {
    method: "POST",
    path: "/auth/logout",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/logout";
}
